### ISSUE TITLE
Item-getting after death

### ISSUE THREAD

**Issue by qubodup** [jaspervdj/JVGS#2]
When I got the hat in the level with the plants, I kept it after my death once. Can't reproduce though. It appears I get a random Item after my death in that level..

**Comment by jaspervdj** [comment]
Well, this is a feature, not a bug (really!). When a friend of me suggested the game was too hard, we had some discussion, and I decided to give the player a random weapon (or no weapon, randomly) every time he spawns.

**Comment by jaspervdj** [comment]
I'm closing this issue since it's not really an issue. I will remove the random item getting, though.
