### ISSUE TITLE
Screen resolution not controllable

### ISSUE THREAD

**Issue by qubodup** [jaspervdj/JVGS#4]
I would like to record a video of jvgs and for that I need it to start at a custom resolution, but it will only full-screen.

Please add a way to allow windowed mode with controllable screen size settings (command line parameters would be best I guess)

**Comment by jaspervdj** [comment]
Okay, I added that in [this commit](http://github.com/jaspervdj/JVGS/commit/eb3119918bb74a71c56e665ed1152130b793c015).
You can now run it with your preferred video size like:

```
./src/jvgs main.lua --width 800 --height 600
./src/jvgs main.lua --fullscreen yes
```

The second options if also the default. I'm not sure, but perhaps this should also be configurable through some xml file?

**Comment by jaspervdj** [comment]
Added some more code. The chosen options are now stored in `data.xml`, so the game will "remember" them. This also means you can edit the video size in `data.xml`. I am now closing this issue.

**Comment by qubodup** [comment]
It works! Thanks!

You should probably add an example line
./src/jvgs main.lua --width 1280 --height 720 --fullscreen no
to the README
